[package]
name = "elisa"
version = "0.1.0"
edition = "2021"

[dependencies]
roborock = { path = "../../lib/roborock" }
transport = { path = "../../lib/transport" }

futures-util = "0.3"

tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "sync"] }
paho-mqtt = "0.13.2"

pretty_env_logger = "0.5"
log = "0.4"

serde_json = "1.0"
