[package]
name = "elizabeth"
version = "0.1.0"
edition = "2021"

[dependencies]
inspinia = { path = "../../lib/inspinia" }
transport = { path = "../../lib/transport" }

futures-util = "0.3"

tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "sync", "signal"] }
paho-mqtt = "0.13.2"

pretty_env_logger = "0.5"
log = "0.4"

md5 = "0.7.0"

serde_json = "1.0"
